// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

// GenreListResponse defines model for GenreListResponse.
type GenreListResponse struct {
	Genres *[]struct {
		Genre string `json:"genre"`
	} `json:"genres,omitempty"`
}
