// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RUzW7bPBB8FWG/76hGStJDwFsPRRD0J0GvhQ+MtJYZiD9drgwYht69ICVaiiUnPbQn",
	"E+Ts7szsWEeorHbWoGEP4gi+2qGW8fiZyFI4OLIOiRXGa0zXfHAIAjyTMg30OWj0Xja4+uYk71YfPEvu",
	"YuOtJS0ZBCjDtzeQJ6wyjA1SALPS6Flq9wpfS8YP4WmqSf37HAh/dYqwBvFzVn8anI+CJvoj2c2pmX1+",
	"wYrD/Hs0hF+V5x/onTUel/Y0ARJPilH7C4AVK86oDrBNf2IhieRhHRYYRb6K2wBd0lzR8q3zqlrSk+1z",
	"p1c3JYnDnLWnS5pyMFL/sdgRnY8cThODCU+tPLRvGq/q2ZxZZtxY+Wol/xNuQcB/xZT+Yox+MRjznvGq",
	"hlnvmfmJaUYXzQ+9lNnaSHgse3Rosk9PD5DDHskra0DA9VUZiFiHRjoFAm6vyqtyTGgUUkx5azBqDJ5I",
	"VtY81DEKfD8gAv2BUETflGX4qaxhNLFQOteqKpYWLz7MT5+D9xxb5i1KrNFXpBwPWh6/RA99p7WkA4jA",
	"N9PB62zQkEUnc2DZ+FMoPGxCVZGcLo6q7t9Sm+yPJpHUyEih3fGMTtyfCqf4b09JHe6nRTN1mM9sOM9X",
	"v/mHvi5Cf8HWHG7Kj39t6vDdXxn13WZpwHKTbvI9LXD6d8RmHmmfdtFRCwJ2zM6LomhtJdud9Szuyruy",
	"kE4V+2voN/3vAAAA//9IoTcHngYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
